config/routes.rb
Bulldogsvolleyballcom::Application.routes.draw do
  root 'home#index'

  get 'schedule' => 'schedule#index', as: 'schedule'
  get 'spring' => 'spring_league#index', as: 'spring_league'
  get 'events/super_scrimmage' => 'events#super_scrimmage', as: 'super_scrimmage'
  get 'events/maroon_and_gold' => 'events#maroon_and_gold', as: 'maroon_and_gold'
  get 'events/mini_camp' => 'events#mini_camp', as: 'mini_camp'

end

app/models/match.rb
class Match
  include Curator::Model

  attr_accessor :opponent, :date, :time, :location, :address, :result, :notes, :tournament

  def initialize(args)
    super(args.merge(id: "#{args[:date].strftime("%Y%m%d%H%M%S")}-#{args[:opponent]}"))
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :hashtag

  protected
  # Nicely identify what is getting pushed to views
  def self.expose(*variable_names)
    variable_names.each do |variable_name|
      define_method((variable_name.to_s+"=").to_sym) do |value|
        @exposed ||= Hash.new
        @exposed[variable_name]= value
      end
      private (variable_name.to_s+"=").to_sym

      define_method(variable_name) do
        @exposed ||= Hash.new
        Maybe(@exposed[variable_name])
      end

      helper_method variable_name
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def super_scrimmage; end

  def maroon_and_gold; end

  def mini_camp; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  expose :next_matches

  def index
    self.next_matches = MatchRepository.next(4)
  end
end

app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController
  expose :matches

  def index
    self.matches = MatchRepository.all.sort{|x,y| x.date <=> y.date}
  end
end

app/controllers/spring_league_controller.rb
class SpringLeagueController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/maroon_and_gold.html.haml
.row
  / Main Content Section
  / This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens
  .large-9.push-3.columns
    %h3.maroon
      Maroon & Gold Tournament
      %small April 11, 2015
    %p
      Doors will open at 8:15AM. Camp areas will be designated for each team. Please locate your teams area and keep your belongings there. Please cleanup your areas before leaving. Locker rooms will be available for athletes to change.
    %p
      Please do not bring chairs. Plenty of seating will be available.
    %p
      Cost of admission is $5 per adult. Students are Free.
    %p
      There will be a concession stand available and it is located around the corner from the Upper gym.
    %p
      We will provide warm up balls for both courts. Please do not bring your own. Do not remove any balls from the gym. We are providing them as a courtesy and conveinence of the teams so ensure your players do not leave with anything that does not belong to them so we can continue to do so.
    %p
      1st and 2nd place teams will receive awards.
    %p
      Play begins promptly at 9AM. Two courts will be in use; one in the Upper gym and the other in the Lower gym. 
    %p
      The first round of play will begin with a 20 minute warmup (3-7-7-3). This time begins at 8:40AM for the 9AM round. Each subsequent round will follow a 4-4-2 warmup. All matches are 3 games to 25 points.
    %p 
      All teams are guaranteed 3 matches. Teams should be ready to play immediately following the previous match. If the previous match completes in 2 games, the next match will start ahead of schedule. The team on the upper portion of the bracket shall be considered the home team for the purposes of the coin flip and scoreboard.
    %p 
      Each team will supply a line judge for their off match. The line judge should be a varsity player or an adult traveling with the team.
    %p
      Tournament seeding will occur one week prior to the tournament based on reported results on the OHSBVA website. Please make sure your team's results are up to date.

    %p
      Teams who will be competing this year:
      %ul
        %li Hoban
        %li Stow
        %li Northmont
        %li Centerville
        %li St Francis De Sales
        %li Farrell (PA)
        %li Mt Vernon
        %li Dublin Coffman
      
    %p
      / = link_to image_tag("2014MaroonAndGoldTournamentBracket.png"), "/MaroonAndGoldTournament2014.pdf", target: "_blank"

  / Nav Sidebar
  / This is source ordered to be pulled to the left on larger screens
  .large-3.pull-9.columns
    %p
      = image_tag "2014StowVolleyballGraphic.png"

app/views/events/mini_camp.html.haml
.row
  .large-9.push-3.columns
    %h3.maroon
      Bulldogs Mini Camp
      %small May 22, 2014
    %p
      Join us for a fun, combined skills mini-camp, where athletes will get conditioned, learn about volleyball, and meet the high school team! Any player from ages 7 to 14 are welcome to attend. Have your athlete wear shorts and a t-shirt. It is important to keep hydrated in the heat, so please bring water. Lots and lots of water!
    %p
      %li Ages 7-10 5:00pm - 6:30pm
      %li Ages 11-14 6:30pm - 8:00pm
    %p
      Stow Munroe Falls High School is located at:
      %br
      = link_to "3227 Graham Rd, Stow, OH 44224",  "https://www.google.com/maps/search/#{CGI.escape('3227 Graham Rd, Stow, OH 44224')}", target: "_blank"

    %p
      You can 
      = link_to "register online now", "http://minicamp.bulldogsvolleyball.com"
      or send a check for $10 made out to "Stow Boys Volleyball" with your registration form to: 
    %p  
      %address
        .adr
          .name Boys Volleyball
          .attn attn: Coach Snyder
          .street-address 3227 Graham Rd
          .locality Stow, OH 
          .postal-code 44224
    
    %p
      = link_to "Download the Registration Form", "/2014BulldogsVolleyballMiniCamp.pdf", target: "_blank"

  / Nav Sidebar
  / This is source ordered to be pulled to the left on larger screens
  .large-3.pull-9.columns
    %p
      %div{style: "width:195px; text-align:center;"}
        %iframe{allowtransparency: "true", frameborder: "0", height: "493", marginheight: "0", marginwidth: "0", scrolling: "no", src: "https://www.eventbrite.com/countdown-widget?eid=11463392315", width: "195"}
        %div{style: "font-family:Helvetica, Arial; font-size:10px; padding:5px 0 5px; margin:2px; width:195px; text-align:center;"}
          %a{href: "http://www.eventbrite.com/r/ecount", style: "color:#ddd; text-decoration:none;", target: "_blank"} Online event registration
          %span{style: "color:#ddd;"} for
          %a{href: "https://www.eventbrite.com/e/boys-volleyball-mini-camp-tickets-11463392315?ref=ecount", style: "color:#ddd; text-decoration:none;", target: "_blank"} Boys Volleyball Mini-Camp
          %span{style: "color:#ddd;"} powered by
          %a{href: "http://www.eventbrite.com?ref=ecount", style: "color:#ddd; text-decoration:none;", target: "_blank"} Eventbrite

app/views/events/super_scrimmage.html.haml
.row
  / Main Content Section
  / This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens
  .large-9.push-3.columns
    %h3.maroon
      Super Scrimmage
      %small March 17, 2018
    %p
      We will have a full gym for the Super Scrimmage this season!! Doors will open at 8:15AM and the first round of the Super Scrimmage will start at 9AM. There will be a 2-6-6-3-3 warmup on your first court starting at 8:40AM. The scrimmage will be over by noon. Each individual scrimmage will last 20 minutes, with 5 minutes allowed to switch courts as needed. Locker rooms will be available, but I encourage you to have your teams come dressed to play.

    %p
      Again we will be providing balls to warm up with, please do not bring your own. All the balls must stay in the gym and make sure your players return them to the carts after they are finished warming up with them. We host this event at a minimal cost, but if volleyballs start disappearing we will no longer be able to do that.

    %p
      Officials will again be volunteering to officiate this event. Please exercise patience with them and remember this is a scrimmage. Any coaches or players that act out of line towards an official will be asked to leave. If you have a problem with a particular official, you can approach me in between matches about it and I will handle the situation.

    %p
      Confirmed Teams:
      %ul
        %li Stow
        %li Hoban
        %li Kent
        %li Hudson
        %li VASJ
        %li Jackson
        %li Brunswick
        %li St Edwards

    %p
      Admission for spectators is free and bleachers will be setup in both gyms. Please, no chairs in either gym.
    / = link_to image_tag("2014SuperScrimmageSchedule.png"), "/2014SuperScrimmageSchedule.pdf", target: "_blank"


  / Nav Sidebar
  / This is source ordered to be pulled to the left on larger screens
  .large-3.pull-9.columns
    %p
      = image_tag "2017-hawaii-night-reaction.jpg"
    %p
      / %img{src: "http://placehold.it/320x240&text=Ad"}/

app/views/home/index.html.haml
.row
  .large-12.columns
    .show-for-medium
      .orbit{role: 'region', 'aria-label': "SMFHS Boys Volleyball Pictures", 'data-orbit': true}
        .orbit-wrapper
          %ul.orbit-container
            %li.orbit-slide.is-active
              %figure.orbit-figure
                =image_tag "2017-stow-vs-jackson-hawaii-night.jpg", class: "orbit-image", alt: "2017 Stow vs Jackson Hawaii Night"
            %li.orbit-slide
              %figure.orbit-figure
                = image_tag "2017-sft-baer.jpg", class: "orbit-image", alt: "2017 Spike for Tykes"
            %li.orbit-slide
              %figure.orbit-figure
                = image_tag "2017-polar-bear-lundstrum.jpg", class: "orbit-image", alt: "2017 Polar Bear Bash"
            %li.orbit-slide
              %figure.orbit-figure
                = image_tag "2017-polar-bear-sibbel-freidt.jpg", class: "orbit-image", alt: "2017 Polar Bear Bash"
            %li.orbit-slide
              %figure.orbit-figure
                = image_tag "2017-polar-bear-gray.jpg", class: "orbit-image", alt: "2017 Polar Bear Bash"
          %nav.orbit-bullets
            %button.is-active{'data-slide': 0}
            %button{'data-slide': 1}
            %button{'data-slide': 2}
            %button{'data-slide': 3}
            %button{'data-slide': 4}

.row#dates
  .large-12.columns
    .row
      - next_matches.each do |match|
        .large-3.small-6.columns
          .event
            .title
              - if match.tournament
                = match.opponent
              - else
                = "Stow vs. #{match.opponent}"
            .date
              .dayname= match.date.strftime("%A")
              .month= match.date.strftime("%B")
              .day= match.date.strftime("%-d")
              .time= "@ #{match.time}"
            %h6.panel
              = link_to match.location, "https://www.google.com/maps/search/#{CGI.escape(match.address)}", target: "_blank"
              %br/
              .address= match.address

.row
  .hide-for-large
    .large-12.columns
      .row
        .large-8.columns
          .row
            .large-4.columns
              .callout.large
                %h5 2019 Open Gyms
                %ul
                  %li Feb 2, 7:00 - 8:30 PM
                  %li Feb 12, 7:00 - 8:30 PM
                  %li Feb 14, 7:00 - 8:30 PM
                  %li Feb 19, 5:00 - 6:30 PM
                  %li Feb 21, 7:30 - 8:30 PM
                  %li Feb 23, 2:30 - 4:00 PM
                  %li Feb 25, 6:00 - 7:30 PM
                  %li Feb 27, 6:00 - 7:30 PM
                  %li Mar 2, 10:00AM - 11:30 AM
                %p
                  %b Tryouts are March 4 @ 5:30 PM
            .large-4.columns.show-for-medium
              .callout.large
                %h5.subheader
                  "The opportunity to play high school volleyball changed the path of my life. It led to a college scholarship, and the ability to get a degree from a great university."
                %br
                %i - Ben Spurlock '04
      .row
        .large-8.columns
          %a.large.button.expand{href: schedule_url} View the full schedule! 
          %a.large.button.expand{href: "http://ww.twitter.com/stow_mvb"} Follow us on Twitter!
          %a.large.button.expand{href: "mailto:coach@bulldogsvolleyball.com"} Email Coach!

  .show-for-large
    .large-12.columns
      .row
        / Content
        .large-8.columns
          .panel.radius.callout
            .row
              .large-6.small-6.columns
                %h4 2019 Open Gyms
                %hr/
                %h5.subheader
                  "The opportunity to play high school volleyball changed the path of my life. It led to a college scholarship, and the ability to get a degree from a great university."
                  %br
                  %i - Ben Spurlock '04
              .large-6.small-6.columns
                %ul
                  %li Feb 2, 7:00 - 8:30 PM
                  %li Feb 12, 7:00 - 8:30 PM
                  %li Feb 14, 7:00 - 8:30 PM
                  %li Feb 19, 5:00 - 6:30 PM
                  %li Feb 21, 7:30 - 8:30 PM
                  %li Feb 23, 2:30 - 4:00 PM
                  %li Feb 25, 6:00 - 7:30 PM
                  %li Feb 27, 6:00 - 7:30 PM
                  %li Mar 2, 10:00AM - 11:30 AM
                %p
                  %b Tryouts are March 4 @ 5:30 PM

        .large-4.columns        
          %a.large.button.expand{href: schedule_url} View the full schedule!
          %a.large.button.expand{href: "http://ww.twitter.com/stow_mvb"} Follow us on Twitter!
          %a.large.button.expand{href: "mailto:coach@bulldogsvolleyball.com"} Email Coach!

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    / Apple iOS Settings
    %link{:href => "/favicon.ico", :rel => "shortcut icon"}
    %link{:rel => "apple-touch-icon", :sizes => "114x114", :href => "/assets/apple-touch-icon-114x114.png"}
    %link{:rel => "apple-touch-icon", :sizes => "72x72", :href => "/assets/apple-touch-icon-72x72.png"}
    %link{:rel => "apple-touch-icon", :href => "/assets/apple-touch-icon.png"}

    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}
    %meta{:content => "default", :name => "apple-mobile-web-app-status-bar-style"}
    %meta{:content => "width=device-width, minimum-scale=1, maximum-scale=1", :name => "viewport"}
    %link{:href => "/assets/ios_icon.png", :rel => "apple-touch-icon-precomposed"}

    %title= content_for?(:title) ? yield(:title) : "Stow Munroe Falls High School Boys Volleyball"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = javascript_include_tag :modernizr
    = csrf_meta_tag

  %body
    .row
      .large-12.columns
        / Navigation
        .title-bar{"data-hide-for" => "medium", "data-responsive-toggle" => "menu"}
          %button.menu-icon{"data-toggle" => "menu", :type => "button"}
          .title-bar-title Site Menu

        #menu.top-bar
          .top-bar-left
            %ul.small-vertical.dropdown.menu{"data-dropdown-menu" => ""}
              %li
                %b
                  = link_to "Stow High School Boys Volleyball", root_url
              %li
                = link_to "Schedule", schedule_url
              %li
                = link_to "Super Scrimmage", super_scrimmage_url
              %li
                .menu-text Youth Programs
                %ul.vertical-menu
                  %li= link_to "Spring 4x4 Program", spring_league_url
                  %li= link_to "Summer Sand 2v2", "http://bivl.org/sand"
                  %li= link_to "Fall Instructional", "http://bivl.org/leagues"
              %li
                = link_to "Spike for Tykes", "http://spikefortykes.org"

    %br/
    = yield

    / Footer
    %footer.row
      .large-12.columns
        %hr/
        .row
          .large-6.columns
            %p © Stow Munroe Falls High School Boys Volleyball
          .large-6.columns
            %ul.inline-list.right
              %li
                = link_to "OHSBVA", "http://www.ohioboysvolleyball.com"
              %li
                = link_to "SMF School District", "http://www.smfschools.org"
              %li
                = link_to "SMF Boosters", "http://www.smfboosters.com"


    = javascript_include_tag "application"

app/views/schedule/index.html.haml
.row
  .large-12.columns
    .row
      .large-12.columns
        .row#dates
          - matches.each do |match|
            .large-3.small-6.columns
              .event
                .title
                  - if match.tournament
                    = match.opponent
                  - else
                    = "Stow vs. #{match.opponent}"
                .date
                  .dayname= match.date.strftime("%A")
                  .month= match.date.strftime("%B")
                  .day= match.date.strftime("%-d")
                  .time= "@ #{match.time}"
                %h6.panel
                  = link_to match.location, "https://www.google.com/maps/search/#{CGI.escape(match.address)}", target: "_blank"
                  %br/
                  .address= match.address

app/views/spring_league/index.html.haml
.row
  / Main Content Section
  / This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens
  .large-9.push-3.columns
    %h3.maroon
      Spring Boys 4x4 League
      %small March 20 - April 14, 2019
    %p
      Boys volleyball is growing in Ohio! 85 High schools now have boys programs and 7 universities have added varsity programs in the last 5 years with more to follow next year. Now is the perfect time to see if your son has the skills to be a volleyball player. The one regret High School players have is that they did not start playing sooner, largely because the opportunities did not exist then, but they do now!
    %p
      This Spring we are inviting athletes in grades 5 thru 8 are to participate in a boys volleyball league. Teams will consist of either all 5th and 6th graders or 7th and 8th graders. Multiple teams will be formed and compete against other schools in NEO.
    %p
      Four practices will be held at Stow Munroe Falls High School on Wednesday evenings  7:30 - 9:00 PM and will be led by the Stow Boys Varsity Team players and staff.
      %ul
        %li March 20, 27
        %li April 3, 10
    %p
      Teams will compete in 2 tournaments on April 7 & 14 at Hiram College and Mount Union. At the tournaments the teams will compete against teams 
      from Kent, Jackson, and other area schools.
    %p
      Cost to register is $75 per athlete. The registration deadline is March 17th.
    %p
      No prior experience is required. All of the coaching needed will be provided by our coaching staff.
    %p
      %b Register online using TeamSnap at
      = link_to "https://go.teamsnap.com/forms/182108", "https://go.teamsnap.com/forms/182108"
    %p= image_tag "2018SpringLeagueChamps.png"
  / Nav Sidebar
  / This is source ordered to be pulled to the left on larger screens
  .large-3.pull-9.columns
    %p
      = image_tag "sidebar-2017-stow-sibbel-devore.jpg"